# This is a basic workflow to help you get started with Actions

name: Build Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 build_windows_desktop:
   name: "Build Windows Desktop"
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: flutter config --enable-windows-desktop
     - run: flutter build windows
     - name: 'Upload Windows Artifact'
       uses: actions/upload-artifact@v2
       with:
          name: windows_64
          path: build/windows/runner/Release/
  
 build_linux_desktop:
   name: "Build Linux Desktop"
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - run: flutter config --enable-linux-desktop
     - run: flutter build linux    
     - name: 'Upload Linux Artifact'
       uses: actions/upload-artifact@v2
       with:
          name: linux_64
          path: build/linux/x64/release/bundle/  

     
 build_macos_desktop:
   name: "Build MacOS Desktop"
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: flutter config --enable-macos-desktop
     - run: flutter build macos
          
     
